### ISSUE TITLE
jsDoc Files auf Server laden

### ISSUE THREAD

**Issue by GitJ1** [jay-hae/SE-Projekt-I3#110]

**Comment by GitJ1** [comment]
jsDoc Files auf Serverladen und Link für die Softwaredokumentation bereitstellen

**Comment by jay-hae** [comment]
das sind doch html files oder? können die nicht dierekt in dem Tab für die Handbücher verlinkt werden ?
dann müssen die nicht extra auf dem Server sodern sind gleich in github drin oder?

**Comment by GitJ1** [comment]
die müssen grundsätzlich irgendwo öffentlich zugänglich liegen, so dass auf sie verlinkt werden kann. Ob das Repo geht, weiß ich halt nicht.
