### ISSUE TITLE
Domain-Modell

### ISSUE THREAD

**Issue by jay-hae** [jay-hae/SE-Projekt-I3#18]
Es fehlt die Multiplizität bei der Beziehung von Hochschule zu Fakultät, da müsste bei Fakultät 1..* hin oder?

**Comment by GitJ1** [comment]
- Mentor muss gegenüber Fakultät Komposition (nicht Aggregation) sein. Ohne Fakultät kein Mentor
- an Fakultät in Richtung Hochschule noch die Multiplizität 1..* (Eine Fakultät kann nur an einer Hochschule sein)
