### ISSUE TITLE
Risikoanalyse

### ISSUE THREAD

**Issue by GitJ1** [jay-hae/SE-Projekt-I3#2]
Es soll eine Risklist in Excel angelegt werden, die entsprechend der Vorgaben der Vorlesungsunterlagen Mögliche Risiken für das Projekt zu erkennen und zu bewerten sowie Maßnahmen zu entwickeln und festzuhalten, die das Eintreten dieser Risiken minimieren.

**Comment by romanpxg** [comment]
risk_list.xlsx angelegt und hochgeladen (Issue #2)
[risk_list.xlsx](https://github.com/jay-hae/SE-Projekt-I3/files/7687263/risk_list.xlsx)

**Comment by romanpxg** [comment]
Risk_List angelegt und hochgeladen (Issue #2)

[new_risk_list.xlsx](https://github.com/jay-hae/SE-Projekt-I3/files/7687333/new_risk_list.xlsx)

**Comment by pthielemann** [comment]
Ich habe die Excel Datei mal per push ins Repository hochgeladen, der close war unbeabsichtigt. Falls du schon fertig bist kannst die Issue ja wieder schließen
