### ISSUE TITLE
aktueller Prototype auf die VM bringen und SI zur verfügung stellen

### ISSUE THREAD

**Issue by jay-hae** [jay-hae/SE-Projekt-I3#25]
Prototyp der SI geben und um Feedback bitten

**Comment by jay-hae** [comment]
Ich benötige vor her den groben Umriss des Funktions umfangs für die SI.

**Comment by pthielemann** [comment]
Ansichtswechsel zwischen allen Ländern, Mentoren, Fakultäten, Studiengängen und Partnerhochschulen.
Mentoren filtern.
Partnerhochschulen alle anzeigen + Filtern/sortieren, neue Partnerhochschulen + ihre Partnerschaft anlegen

Editieren möglich, wird aber noch nicht in der Datenbank gespeichert, mobility agreements kann man Stand jetzt, noch nicht einsehen (mach ich vllt übers WE)
