### ISSUE TITLE
README lesen, diesen Issue kommentieren falls Fragen

### ISSUE THREAD

**Issue by jay-hae** [jay-hae/SE-Projekt-I3#37]
Bitte bis Spätestens Montag vor Retro Workshop

**Comment by GitJ1** [comment]
Überschrift Agenda: 
was soll das heißen?
"neue, in dem Gespräch aufkommende TOP's sind "

**Comment by jay-hae** [comment]
Oh danke da hab ich vergessen den Satz zu beenden...
Sollte jetzt richtig sein
