### ISSUE TITLE
Constraints aus der Datenbank herausfinden

### ISSUE THREAD

**Issue by pthielemann** [jay-hae/SE-Projekt-I3#54]
Wann kann etwas in der Datenbank gelöscht werden? Welche Abhängigkeiten bestehen

**Comment by jay-hae** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/SE-Projekt-I3-62544009cd3b9000233ac11a/issues/jay-hae/SE-Projekt-I3/54?planning-poker) with ZenHub @GitJ1 @pthielemann @thanhhakhuong @Angrybox1 @lucamsz @nicoro7 @romanpxg

**Comment by jay-hae** [comment]
Siehe Raphael Datenbank diagramm.
- Raphael löscht rekursiv
-  unbedingt mit Raphael in kontakt treten

**Comment by jay-hae** [comment]
Ist hier die Frage wie man das erworbene Wissen weiter gibt... es sei denn man programmiert selbst die SQL abfragen...

**Comment by jay-hae** [comment]
okay ich hab dafür jetzt was....
Das steht in einer Textdatei in docs/development/loeschen_vorgehen.txt und ist so auch noch mal in der Bertiebsdoku von der Vorgruppe unter docs/deployment/ letzte Seite zufinden
