### ISSUE TITLE
Repository auf Rechner klonen

### ISSUE THREAD

**Issue by GitJ1** [jay-hae/SE-Projekt-I3#6]
Alle Teilnehmer des Teams I3 sollen das von Jakob Häcker erstellte Repository auf ihren Rechner klonen und prüfen, ob push/pull funktioniert.

**Comment by pthielemann** [comment]
Ich denke mittlerweile sollte es jeder haben oder? Dann können wir die Issue nämlich schließen.

**Comment by GitJ1** [comment]
Alle Teammitglieder von I3 haben Repository erfolgreich auf ihren Rechner geklont und push/pull Funktion getestet.
