### ISSUE TITLE
Alphabetische Sortierung Funktioniert nicht

### ISSUE THREAD

**Issue by jay-hae** [jay-hae/SE-Projekt-I3#61]
unter: http://141.56.137.83:5000/homepage/institutes
und http://141.56.137.83:5000/homepage/courses
wird keine Alphabetische Sortierung vorgenommen.
weder in den Filtern noch in der tablearischen Anzeige

**Comment by jay-hae** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/SE-Projekt-I3-62544009cd3b9000233ac11a/issues/jay-hae/SE-Projekt-I3/61?planning-poker) with ZenHub @GitJ1 @pthielemann @thanhhakhuong

**Comment by thanhhakhuong** [comment]
- Sortierung bei Tabelle Studiengänge
- Sortierung bei Tabelle Mentoren: nach Nachname sortiert und Nachname in der Tabelle nach links verschoben
- Sortierung bei Tabelle Fakultäten
- Sortierung bei Tabelle Länder
- Sortierung der Filter auf Seite Hochschule: Land, Fakultät, Vertragstyp
