### ISSUE TITLE
Login seite erstellen

### ISSUE THREAD

**Issue by jay-hae** [jay-hae/SE-Projekt-I3#63]
-Login nicht im Quelltext sondern direkt die normalen Dtenbank logins als Login verwenden. So müssen diese Daten nicht gepspeichert werden!!

**Comment by pthielemann** [comment]
das ist genau das was wir machen :D, nur dass es noch nicht endgültig implementiert ist und ich's daher im Quelltext als static Daten eingetragen habe, um mich beim implementieren nicht immer anmelden zu müssen
