### ISSUE TITLE
UC Spezifikation der Berichte/Statistiken

### ISSUE THREAD

**Issue by jay-hae** [jay-hae/SE-Projekt-I3#64]
-DRINGEND: Statistik: Wie kommen die Daten auf unsere Webseite wenn wir Studentendaten nicht verarbeiten. zB Exceltabelle mittels ODBC via SQL Befehlen abfragen. ZB nur die Anzahl der Studenten
Raphael hat alle erforderlichen Berichte in seiner Gruppe erklärt. Wobei diee Art von Berichten nicht gefordert wurden.
Fragestellung: Kommen von einer Universität viele Studierende es geht aber keiner der eigenen Studierenden an die entsprechenden Universitäten. => In welchem Zeitraum sind wie viel Studierenden rein und wie viel Raus.
(aus Protokoll vom 2.5.)

**Comment by jay-hae** [comment]
- welche Berichte werden von SI benötigt?

**Comment by pthielemann** [comment]
was meinst du denn mit "wie kommen die Daten auf unsere Website?" 
In unserem Programm sollten keine Studentendaten gepflegt werden, also machen wir das auch nicht. Irgendwann muss mal schluss sein, es kommen nach jedem Meeting neue Anforderungen welche wieder in eine ganz andere Richtung gehen??

**Comment by jay-hae** [comment]
- PDF und Excel wären gut.
In erster Linie Excel da damit auch PDF erstellt werden können.
Wenn möglich beides. Über ODBC Driver.

Bitte UC Spezifikation dem entsprechend aktualiseiren

**Comment by jay-hae** [comment]
genauso UC6
