### ISSUE TITLE
 Bug2: Filter "Aktive verträge" ändern

### ISSUE THREAD

**Issue by jay-hae** [jay-hae/SE-Projekt-I3#72]
Hier soll direkt erkenn bar werden was damit gemeint ist. Die Bedeutung erschließt sich nicht direkt.
unter /homepage/institutes

**Comment by GitJ1** [comment]
app.py Zeilen 127 bis 130 ändern von Key 'filter-shown' zu 'filter_activity'

**Comment by GitJ1** [comment]
modal_edit_functionality.js Zeilen 58 bis 60
Ausgabe der Aktivität geändert statt 0/1 nun Ausgabe Ja/Nein

**Comment by GitJ1** [comment]
institutes.html 

Filterbezeichnung: Aktive Verträge mit auswahl ja/nein war unklar

Nun: "Gesamtanzahl Verträge" mit Auswahl "Nur aktive Verträge" und "Nur inaktive Verträge"
