### ISSUE TITLE
Bug 3: bei Partnerschaften -> Vertragstypen als Reiter oder Tabs nicht Dropdown

### ISSUE THREAD

**Issue by jay-hae** [jay-hae/SE-Projekt-I3#73]
- Bug3: Hochschule -> bearbeiten Modal (Hochschule Bearbeitungsansicht) -> Partnerschaften (Verträge)-> Vertragstyp eher kein Dropdown sondern eher wie verschieden Reiter, da ohnehin nie kein Vertragstyp ausgewählt sein darf (Defaultwert: Hochschulvertrag)

**Comment by pthielemann** [comment]
wie soll ich mir das vorstellen? Wollen die da 8 verschiedene Ansichten, für jeden Typ eine oder was?

**Comment by GitJ1** [comment]
So wie Raphael es beschrieben hat, soll immer eine Vertragsart ausgewählt sein und nie keine Auswahl.
Das heißt es muss ein Vertragstyp default sein und dann nur die Verträge diesen Typs angezeigt werden. Wird der Vertragstyp geändert sollen nur diese Verträge zu sehen sein etc.
Gleichzeitig soll immer klar zu sehen sein, welcher Vertragstyp gerade ausgewählt wurde. Kann natürlich auch ein Dropdown sein. Die Krititk daran war nur, dass man dann unnötik klicken muss (Dropdown click => Vertragstyp click) statt nur Vertragstyp click weißt du?

**Comment by GitJ1** [comment]
es gibt keinen expliziten Standardvertrag. Einfach so wie es jetzt ist. Erster Vertrag in der Liste ist ausgewählt. Niemals kein Vertrag
- Erstmal keine Auswahl und dementsprechend nichts anzeigen und dann Auswahl über Drop-Down-Menü welcher Vertragstyp. Also User zwingen einen Vertragstyp auszuwählen bevor etwas angezeigt wird.

**Comment by pthielemann** [comment]
also wollte nur mal ein Update dazu geben: 
als einzelne Reiter setzen wir es nicht um, ich würde es jetzt einfach als Dropdown lassen, alles andere beschert unnötigen Programmieraufwand den wir zeitlich nicht umgesetzt bekommen, da gibt es wesentlich wichtigere Dinge zu tun, und ich glaube der eine Klick wird sie jetzt auch nicht umbringen, einen Filter anwenden ist jetzt nicht unbedingt aufwendig

**Comment by GitJ1** [comment]
klar klar! Wichtig ist nur, dass NIE keine Auswahl besteht!

**Comment by pthielemann** [comment]
also wie jetzt? oben steht einmal, man muss zuerst einen Typ auswählen bevor was angezeigt wird & es wird gefordert dass der 1. Vertrag aus der Liste als "Standard" eingestellt sein soll? Weiß jetzt nicht welche der beiden ich implementieren soll ^^

**Comment by pthielemann** [comment]
aktuellste Version beinhaltet zurzeit noch "Keine Auswahl", es wird aber durch einen Bug die Hochschulpartnerschaften direkt ausgewählt, also schaut es euch am besten einfach mal an, teste ein wenig und sag mir ob das den Vorstellungen entspricht.
