### ISSUE TITLE
Bug4: Button Mentoren => bearbeiten funktioniert nicht

### ISSUE THREAD

**Issue by jay-hae** [jay-hae/SE-Projekt-I3#74]

**Comment by GitJ1** [comment]
Mentoren öffnen und schließen funktioniert wieder.
Fehler besteht im ziehen der Daten aus Datenbank.

**Comment by GitJ1** [comment]
Mentoren Bearbeiten hat noch keinen speichern und abbrechen Button

**Comment by GitJ1** [comment]
Wir haben in Querriey.py Abfrage an Datenbank "for_mentor_modal" angelegt
und mentor_modal_edit.js  so angepasst, dass dieses die Abfrage in Querries.py anstößt.

Wird nun im Reiter Mentoren auf Bearbeiten gedrückt, werden die aktuellen Daten des Mentors angezeigt.

Außerdem sind nun die Buttons Abbrechen und Speichern sichtbar.
