### ISSUE TITLE
Bug 5: Unter Mentoren => anlegen => abbrechen und speichern Button funktionieren nicht 

### ISSUE THREAD

**Issue by jay-hae** [jay-hae/SE-Projekt-I3#75]

**Comment by GitJ1** [comment]
Ebenso im Modal Hochschulen funktioniert Abbrechen und Speichern nicht

**Comment by GitJ1** [comment]
Bei Mentoren funktioniert der Abbrechen Button insofern, dass das Modal sich schließt allerdings werden die Einträge aus den Textfeldern noch nicht gelöscht!

**Comment by GitJ1** [comment]
schließen Button funktioniert wieder nicht

**Comment by GitJ1** [comment]
Im Abbrechen-Button haben sich classe close_modal_edit und ein direkte toggle() Befehl blockiert.
Abbrechen funktioniert
