### ISSUE TITLE
WF anlegen für Berichte (UC 6-7)

### ISSUE THREAD

**Issue by jay-hae** [jay-hae/SE-Projekt-I3#77]

**Comment by jay-hae** [comment]
Am besten bis Donnerstag oder Freitag

Wäre cool wenn wir hier mal figma ausprobieren um das parallel zu machen...

**Comment by pthielemann** [comment]
@jay-hae wie siehts mit dem Entwurf dazu aus? Welche werden gebraucht etc. wäre langsam gut das mal gebündelt zu haben um die Implementierung dahingehend voranzutreiben
