### ISSUE TITLE
Abnahme Protokoll korrektur lesen

### ISSUE THREAD

**Issue by jay-hae** [jay-hae/SE-Projekt-I3#86]
siehe Vorgruppe in docs/deployment/Abnahmeprotokoll

**Comment by jay-hae** [comment]
muss fertig bis zum 24.06 sein,

das Protokoll muss verbessert am 8.7 abgegeben werden

**Comment by jay-hae** [comment]
Abnamheprotokoll fertig, sollte korrektur gelesen werden

**Comment by GitJ1** [comment]
Done
