### ISSUE TITLE
Softwaredokumentation

### ISSUE THREAD

**Issue by thanhhakhuong** [jay-hae/SE-Projekt-I3#89]
− Namen und Beschreibung aller Klassen
− Namen, Kurzbeschreibung sowie Parameter aller Funktionen pro Klasse

**Comment by jay-hae** [comment]
Herr Anke hat ein Tool vorgestellt, das automatische SW Dokus erstellt: Doxygen
Zu finden auch in entsprechenden VL Folien.
Vielleicht ist es was für euch :)
