### ISSUE TITLE
Nutzungsbedingungen / Lizenzen

### ISSUE THREAD

**Issue by jay-hae** [jay-hae/SE-Projekt-I3#92]
Vermutlich ein Text zur Software der die Nutzungsbedingugnen beschreibt

- Open Source: diverse Lizenzbedingungen verfügbar Auswahl z.B. mit https://choosealicense.com/

siehe Organisation_Belegarbeiten_2022.pdf
Folie 6

abgabe: 24.06

**Comment by nicoro7** [comment]
kommt dann in den Projektbericht... Zur Zeit in Readme.md gespeichert

**Comment by jay-hae** [comment]
alles klar Danke. aber mir erklärt sich nicht warum das in den Projektbericht muss... ich erfrage das in einem Praktika
